version: '3.8'

services:
  sqlserver-hangfire:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "*/HangfirePassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"