version: '3.8'

services:
  mongo:
    image: mongo:6.0.3
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - 27017:27017

